### ISSUE TITLE
Indentation incorrect for syntax completed environment

### ISSUE THREAD

**Issue by Chais** [James-Yu/Atom-LaTeX#20]
If I start a line with `\be` and select the `begin` completion the resulting environment is indented by 2 spaces instead of one 4 spaces wide tab, that is configured everywhere. All of Atom-LaTeX' grammars adopted Atom's default of 4 space tab length.

Am I looking at the wrong configs?

**Comment by James-Yu** [comment]
Can you please give a screenshot of your 'tab length' setting in LaTeX grammar section of Atom-LaTeX setting page?

**Comment by Chais** [comment]
![screenshot from 2017-03-15 13-37-05](https://cloud.githubusercontent.com/assets/1783098/23948768/cb3e73c0-0984-11e7-8e76-0f6635dbf6b8.png)
The section is too high to fit in a screen. So I included the following heading, hoping the sections are always in the same order.

**Comment by Chais** [comment]
Once I started fiddling around with the settings it seems tab length is now 2 throughout the document, not only in the generated completion. When I set it to anything but 4 it behaves as configured, but with 4 I only get 2.

**Comment by James-Yu** [comment]
Found the problem. Will be fixed in the next update.

**Comment by Chais** [comment]
Thanks a lot. And kudos for the swift response.

**Comment by James-Yu** [comment]
Fixed. Will wait for few days to push it live in atom. See #13 for explanation.

**Comment by Chais** [comment]
![atom_txt](https://cloud.githubusercontent.com/assets/1783098/24102250/9bfc2738-0d7b-11e7-8027-4d17f324185d.png)
![atom_tex](https://cloud.githubusercontent.com/assets/1783098/24102253/9e7f8efa-0d7b-11e7-90f5-9cf0a08afcd1.png)
This isn't fixed for me. All I did between the two pictures was switch the grammar. I tried uninstalling and reinstalling to no avail.

**Comment by James-Yu** [comment]
I cannot reproduce the problem. Whenever you type a `tab`, Atom auto convert it to spaces according to its setting. So changing grammar should not have impact on it. I would recommend you have a check on the editor's setting. Is `tab` to `space` enabled?

**Comment by Chais** [comment]
It's not. I don't like spaces for indentation. I have set Atom to use hard tabs with length 4.

**Comment by James-Yu** [comment]
For your example given just now, the length of `tab` is auto controlled by Atom according to your setting in the grammar page. No explicit conversion is made in the extension. I would say this is an upstream bug.

In the last commit for this issue, the indentation between `\begin` and `\end` was changed from two spaces to a `tab`. You can click on the commit for a check.

Sorry it seems not to be a problem that can be fixed from my side.

**Comment by Chais** [comment]
It doesn't happen for any other grammar though. Even works correctly on LaTeX Beamer, which is also added by atom-latex.

**Comment by Chais** [comment]
I just found out another interesting thing. When I reverted the editor tab width to 2 I had some of atom-latex' grammars set to tab width 2. Others were set to 4, even though they probably should follow the system default. When I set the LaTeX grammar to 4 it correctly gives me tabs with length 4. There's definitely something off with following the defaults. See this [video](https://gfycat.com/PerkyNaiveIberianlynx). Please note that I'm not deleting the 4. I only enter it, it deletes itself, as that is the system default, but atom-latex doesn't adhere to it.

**Comment by James-Yu** [comment]
I am almost sure this is an upstream bug of Atom. Extensions cannot control the behavior of setting items.

**Comment by Chais** [comment]
But wouldn't it affect all settings then? Not just a single one?
